### ISSUE TITLE
"Schreibe Text in den Zustand" erzeugt Fehlermeldungen

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.text2command#15]
Trigger Worte: AZ/Arbeitszimmer Szene/hue
Eingebener Text: hue az kamin

Fehler:

```
text2command.0 | 2018-03-29 03:22:35.891 | error | at return_pub_sub (/opt/iobroker/node_modules/redis/index.js:794:18)
-- | -- | -- | --
text2command.0 | 2018-03-29 03:22:35.891 | error | at RedisClient.emit (events.js:217:7)
text2command.0 | 2018-03-29 03:22:35.891 | error | at emitThree (events.js:136:13)
text2command.0 | 2018-03-29 03:22:35.891 | error | at RedisClient. (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:104:25)
text2command.0 | 2018-03-29 03:22:35.891 | error | at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3395:34)
text2command.0 | 2018-03-29 03:22:35.891 | error | at Adapter.emit (events.js:211:7)
text2command.0 | 2018-03-29 03:22:35.891 | error | at emitOne (events.js:116:13)
text2command.0 | 2018-03-29 03:22:35.891 | error | at Adapter. (/opt/iobroker/node_modules/iobroker.text2command/main.js:85:21)
text2command.0 | 2018-03-29 03:22:35.891 | error | at processText (/opt/iobroker/node_modules/iobroker.text2command/main.js:210:33)
text2command.0 | 2018-03-29 03:22:35.891 | error | at Object.extractText (/opt/iobroker/node_modules/iobroker.text2command/lib/simpleControl.js:409:30)
text2command.0 | 2018-03-29 03:22:35.891 | error | TypeError: words[w].split is not a function
text2command.0 | 2018-03-29 03:22:35.888 | error | pmessage messagebox.system.adapter.text2command.0 {"command":"send","message":{"text":"az hue kamin","id":185100632,"user":"Michael"},"from":"system.adapter.telegram.1","callback":{"message":{"text":
```

**Comment by Apollon77** [comment]
How is the exact configuration? There seems to be a problem in your rules definitions because the error happens.

I added a change and error logging on Github (version number not changed). Please try and tell also logging please for the whole processing of that message (ideally debug)

**Comment by ruhr70** [comment]
Logging auf Debug, Adapter von Github (über Admin, Auswahl -> über Github) installiert.

Das Log ist nun kürzer als vorher, trotz DEBUG:

`

text2command.0 | 2018-04-02 12:25:51.396 | error | TypeError: words[w].split is not a function at Object.extractText (/opt/iobroker/node_modules/iobroker.text2command/lib/simpleControl.js:413:30) at processText (/opt/iobroker/node_modules/iobr
-- | -- | -- | --
text2command.0 | 2018-04-02 12:25:51.396 | error | pmessage messagebox.system.adapter.text2command.0 {"command":"send","message":{"text":"az szene kamin","id":185100632,"user":"Michael"},"from":"system.adapter.telegram.1","callback":{"message":{"text"
text2command.0 | 2018-04-02 12:25:51.396 | info | processText: "az szene kamin"
text2command.0 | 2018-04-02 12:25:51.395 | debug | redis pmessage messagebox.system.adapter.text2command.0 messagebox.system.adapter.text2command.0 {"command":"send","message":{"text":"az szene kamin","id":185100632,"user":"Michael"},"from":"system.a
text2command.0 | 2018-04-02 12:25:34.270 | debug | system.adapter.admin.0: logging true
text2command.0 | 2018-04-02 12:25:34.270 | debug | redis pmessage io.*.logging io.system.adapter.admin.0.logging {"val":true,"ack":true,"ts":1522664734266,"q":0,"from":"system.adapter.admin.0","lc":1522664734266}
text2command.0 | 2018-04-02 12:25:22.613 | info | starting. Version 1.1.6 in /opt/iobroker/node_modules/iobroker.text2command, node: v8.11.1
text2command.0 | 2018-04-02 12:25:22.601 | info | States connected to redis: 0.0.0.0:6379
text2command.0 | 2018-04-02 12:25:22.600 | debug | statesDB connected
text2command.0 | 2018-04-02 12:25:22.593 | debug | objectDB connected
`

**Konfiguration:**

Regel: Schreibe Text in den Zustand
Trigger-Worte: az/Arbeitszimmer szene kamin
Anhalten: gesetzt
Parameter: javascript.0.hue.szene.arbeitszimmer.szene
Parameter Wert zum schreiben: kamin
  (ohne Anführungszeichen)
Antwort: dynamische hue Szene > Kamin < Eingeschaltet

**Comment by Apollon77** [comment]
Dein Log ist leider abgeschnitten ... Bitte aus dem "echten" Logfile auf Platte rauskopieren. Admin schneidet ab.

Bitte nochmal von Github installieren, Hab noch ein Logging eingebaut. Danke

**Comment by ruhr70** [comment]
von Github erneut installiert

`
2018-04-04 18:10:23.428 - info: text2command.0 processText: "az szene kamin"
--
2018-04-04 18:10:23.429 - debug: text2command.0 Words: [["az","arbeitszimmer"],"szene","kamin"]
2018-04-04 18:10:23.429 - error: text2command.0 pmessage messagebox.system.adapter.text2command.0 {"command":"send","message":{"text":"az szene kamin","id":185100632,"user":"Michael"},"from":"system.adapter.telegram.1","callback":{"message":{"text":"az szene kamin","id":185100632,"user":"Michael"},"id":93,"ack":false,"time":1522858223426},"_id":32262704} words[w].split is not a function
2018-04-04 18:10:23.432 - error: text2command.0 TypeError: words[w].split is not a function
at Object.extractText (/opt/iobroker/node_modules/iobroker.text2command/lib/simpleControl.js:414:30)
at processText (/opt/iobroker/node_modules/iobroker.text2command/main.js:210:33)
at Adapter. (/opt/iobroker/node_modules/iobroker.text2command/main.js:85:21)
at emitOne (events.js:116:13)
at Adapter.emit (events.js:211:7)
at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3395:34)
at RedisClient. (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:104:25)
at emitThree (events.js:136:13)
at RedisClient.emit (events.js:217:7)
at return_pub_sub (/opt/iobroker/node_modules/redis/index.js:794:18)
2018-04-04 18:10:48.398 - debug: text2command.0 redis pmessage io.*.logging io.system.adapter.admin.0.logging {"val":false,"ack":true,"ts":1522858248396,"q":0,"from":"system.adapter.admin.0","lc":1522858248396}
2018-04-04 18:10:48.398 - debug: text2command.0 system.adapter.admin.0: logging false
2018-04-04 18:10:49.421 - info: host.iobrokerng2 object change system.adapter.text2command.0
2018-04-04 18:10:49.421 - info: host.iobrokerng2 stopInstance system.adapter.text2command.0
2018-04-04 18:10:49.421 - info: host.iobrokerng2 stopInstance system.adapter.text2command.0 killing pid 8854
2018-04-04 18:10:49.930 - info: text2command.0 terminating
2018-04-04 18:10:49.944 - info: host.iobrokerng2 instance system.adapter.text2command.0 terminated with code 0 (OK)
2018-04-04 18:10:51.945 - info: host.iobrokerng2 instance system.adapter.text2command.0 started with pid 8911
2018-04-04 18:10:52.213 - info: text2command.0 States connected to redis: 0.0.0.0:6379
2018-04-04 18:10:52.231 - info: text2command.0 starting. Version 1.1.6 in /opt/iobroker/node_modules/iobroker.text2command, node: v8.11.1


`

**Comment by Apollon77** [comment]
Das hat geholfen ... Bitte neuer Versuch vom Github

**Comment by ruhr70** [comment]
Hab das Update über Admin/Github gemacht.
Der Fehler ist allerdings immer noch da.

Log kommt morgen

**Comment by GermanBluefox** [comment]
Should be fixed by @Apollon77: https://github.com/ioBroker/ioBroker.text2command/commit/1cb19a718d216022a169250b26b751f48818242a

**Comment by Apollon77** [comment]
@ruhr70 Bitte nochmal neu vom Github versuchen das der codestand passt ...

**Comment by ruhr70** [comment]
funktioniert jetzt :-)

Danke!
