### ISSUE TITLE
Kommandozeile Rolladen auf / zu funktioniert nicht

### ISSUE THREAD

**Issue by LJSven** [ioBroker/ioBroker.text2command#23]
Ich versuche die Rollladen über text2command zu steuern. Leider ohne Erfolgt. Folgende Fehlermeldung erscheint (Version 1.2.4)

> 2018-07-10 12:42:30.466 - info: host.raspberrypi Update repository "latest" under "http://download.iobroker.net/sources-dist-latest.json"
2018-07-10 12:43:11.717 - info: iobroker url "https://github.com/ioBroker/ioBroker.text2command/tarball/master" text2command --debug
2018-07-10 12:43:13.900 - info: iobroker install https://github.com/ioBroker/ioBroker.text2command/tarball/master
2018-07-10 12:43:16.681 - info: iobroker npm install https://github.com/ioBroker/ioBroker.text2command/tarball/master --production --save --prefix "/opt/iobroker" (System call)
2018-07-10 12:44:45.802 - info: iobroker > authenticate-pam@1.0.2 install /opt/iobroker/node_modules/authenticate-pam
> node-gyp rebuild
2018-07-10 12:44:54.838 - info: iobroker make: Verzeichnis „/opt/iobroker/node_modules/authenticate-pam/build“ wird betreten
2018-07-10 12:44:54.847 - info: iobroker CXX(target) Release/obj.target/authenticate_pam/authenticate_pam.o
2018-07-10 12:44:56.941 - info: iobroker ../authenticate_pam.cc:30:31: fatal error: security/pam_appl.h: Datei oder Verzeichnis nicht gefunden #include
^
2018-07-10 12:44:56.943 - info: iobroker compilation terminated.
2018-07-10 12:44:56.987 - info: iobroker authenticate_pam.target.mk:92: die Regel für Ziel „Release/obj.target/authenticate_pam/authenticate_pam.o“ scheiterte
2018-07-10 12:44:56.990 - info: iobroker make: Verzeichnis „/opt/iobroker/node_modules/authenticate-pam/build“ wird verlassenmake: *** [Release/obj.target/authenticate_pam/authenticate_pam.o] Fehler 1
2018-07-10 12:44:57.011 - info: iobroker gyp
2018-07-10 12:44:57.018 - info: iobroker ERR! build error
2018-07-10 12:44:57.036 - info: iobroker gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack at emitTwo (events.js:106:13)
gyp ERR! stack at ChildProcess.emit (events.js:191:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
2018-07-10 12:44:57.044 - info: iobroker gyp ERR! System Linux 4.14.34-v7+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/authenticate-pam
gyp ERR! node -v v6.14.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
2018-07-10 12:45:06.660 - info: iobroker npm
2018-07-10 12:45:06.663 - info: iobroker WARN enoent
2018-07-10 12:45:06.684 - info: iobroker ENOENT: no such file or directory, open '/opt/iobroker/node_modules/prebuild-install/package.json'npm WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 (node_modules/authenticate-pam):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
2018-07-10 12:45:06.693 - info: iobroker + iobroker.text2command@1.2.4updated 1 package and audited 3512 packages in 102.992s
2018-07-10 12:45:06.700 - info: iobroker found 66 vulnerabilities (52 low, 1 moderate, 13 high) run `npm audit fix` to fix them, or `npm audit` for details
2018-07-10 12:45:06.848 - info: iobroker got /opt/iobroker/node_modules/iobroker.text2command/admin
2018-07-10 12:45:06.879 - info: iobroker upload [4] text2command.admin /opt/iobroker/node_modules/iobroker.text2command/admin/words.js words.js application/javascript
2018-07-10 12:45:07.036 - info: iobroker upload [3] text2command.admin /opt/iobroker/node_modules/iobroker.text2command/admin/text2command.png text2command.png image/png
2018-07-10 12:45:07.120 - info: iobroker upload [2] text2command.admin /opt/iobroker/node_modules/iobroker.text2command/admin/tab.js tab.js application/javascript
2018-07-10 12:45:07.203 - info: iobroker upload [1] text2command.admin /opt/iobroker/node_modules/iobroker.text2command/admin/tab.html tab.html text/html
2018-07-10 12:45:07.277 - info: iobroker upload [0] text2command.admin /opt/iobroker/node_modules/iobroker.text2command/admin/langModel.js langModel.js application/javascript
2018-07-10 12:45:07.408 - info: iobroker exit 0
2018-07-10 12:45:08.188 - info: host.raspberrypi Update repository "latest" under "http://download.iobroker.net/sources-dist-latest.json"
2018-07-10 12:45:42.975 - info: host.raspberrypi object change system.adapter.text2command.0
2018-07-10 12:45:42.977 - info: host.raspberrypi "system.adapter.text2command.0" disabled
2018-07-10 12:45:42.983 - info: host.raspberrypi stopInstance system.adapter.text2command.0
2018-07-10 12:45:42.984 - info: host.raspberrypi stopInstance system.adapter.text2command.0 killing pid 728
2018-07-10 12:45:43.501 - info: text2command.0 terminating
2018-07-10 12:45:43.548 - info: host.raspberrypi instance system.adapter.text2command.0 terminated with code 0 (OK)
2018-07-10 12:45:45.680 - info: host.raspberrypi object change system.adapter.text2command.0
2018-07-10 12:45:45.751 - info: host.raspberrypi instance system.adapter.text2command.0 started with pid 1563
2018-07-10 12:45:48.926 - info: text2command.0 starting. Version 1.2.4 in /opt/iobroker/node_modules/iobroker.text2command, node: v6.14.3
2018-07-10 12:47:05.875 - info: text2command.0 processText: "Rollladen hoch"
2018-07-10 12:47:05.901 - info: text2command.0 Response: Raum wurde nicht gefunden
2018-07-10 12:47:10.126 - info: text2command.0 processText: "Rollladen runter"
2018-07-10 12:47:10.129 - info: text2command.0 Response: Es gibt kein Zimmer mit dem Namen
2018-07-10 12:47:18.870 - info: text2command.0 processText: "Rolladen hoch Garage"
2018-07-10 12:47:18.900 - warn: text2command.0 Control of "javascript.0.Rolladensteuerung.EG_Küche_1_Soll" cannot be done, because role is empty
2018-07-10 12:47:18.908 - warn: text2command.0 Control of "javascript.0.Rolladensteuerung.EG_Küche_2_Soll" cannot be done, because role is empty
2018-07-10 12:47:19.061 - error: text2command.0 uncaught exception: Cannot read property 'de' of undefined
2018-07-10 12:47:19.063 - error: text2command.0 TypeError: Cannot read property 'de' of undefined
at Object.sayNoFunctionInThisRoom (/opt/iobroker/node_modules/iobroker.text2command/lib/simpleAnswers.js:181:62)
at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.text2command/lib/devicesControl.js:531:47)
at ontimeout (timers.js:386:11)
at tryOnTimeout (timers.js:250:5)
at Timer.listOnTimeout (timers.js:214:5)
2018-07-10 12:47:19.575 - info: text2command.0 terminating
2018-07-10 12:47:19.612 - error: Caught by controller[0]: TypeError: Cannot read property 'de' of undefined
2018-07-10 12:47:19.614 - error: Caught by controller[0]: at Object.sayNoFunctionInThisRoom (/opt/iobroker/node_modules/iobroker.text2command/lib/simpleAnswers.js:181:62)
2018-07-10 12:47:19.614 - error: Caught by controller[0]: at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.text2command/lib/devicesControl.js:531:47)
2018-07-10 12:47:19.615 - error: Caught by controller[0]: at ontimeout (timers.js:386:11)
2018-07-10 12:47:19.615 - error: Caught by controller[0]: at tryOnTimeout (timers.js:250:5)
2018-07-10 12:47:19.616 - error: Caught by controller[0]: at Timer.listOnTimeout (timers.js:214:5)
2018-07-10 12:47:19.616 - error: host.raspberrypi instance system.adapter.text2command.0 terminated with code 0 (OK)
2018-07-10 12:47:19.617 - info: host.raspberrypi Restart adapter system.adapter.text2command.0 because enabled

**Comment by unltdnetworx** [comment]
Vermutlich etwas spät, aber bei einer Abfrage "Rollladen hoch" fehlt der Raum, also Garage und bei der anderen Abfrage "Rolladen hoch Garage" steht "Rolladen" mit nur zwei LL, es muss aber "Rollladen" heißen.
Außerdem muss die vordefinierte Funktion-Aufzählung "blind", sowie Räume-Aufzählung "garage" dem Datenpunkt des Rollladen zugewiesen sein.

**Comment by GermanBluefox** [comment]
Done
